name: CI

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - "**"
      - "!renovate/**"
    tags:
      - "v**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["14", "16"]

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - uses: actions/cache@v1
        id: cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - run: npm run lint && npm run format:check

      - run: npm run build
